### PR TITLE
Added CI and fixed kron_prod_inv test

### PR DESCRIPTION
**Pull request by Jbwasse2**
Even though I changed the test the problem is still there, I added a test to better describe an example of this test (testFail) in test_kron_inv. However, this is either a bug in math, my understanding of the math, or python, and not our code.

### CODE REVIEW

**Comment by Jbwasse2** [comment]
DO NOT ACCEPT THIS PULL REQUEST! I am getting an error in travis on my master branch after the merge.

**Comment by Jbwasse2** [comment]
Nevermind, the tests that failed are Alli's new tests.

**Comment by Jbwasse2** [comment]
I added an issue for digging deeper into this problem, #16

**Comment by alexandroid000** [comment]
So this is ready for merge or no?

**Comment by alexandroid000** [comment]
Also how does the Travis integration work?

**Comment by Jbwasse2** [comment]
Yes it is ready to merge. Travis is set up on my repo, but you or Tauhid will need to go to https://travis-ci.org/account/repositories and enable this repo in order to get builds to run on Travis. Once you have done that Travis CI will automatically test our code for different versions of python (3.4, 3.5, 3.6, and 3.7). For example, on this pull request you can see how the code passed/failed for different versions of python https://travis-ci.com/Jbwasse2/MarkovChainAnalysis. You can also add other stuff for travis CI to test over like operating systems, but I think it defaults to linux.

**Comment by Jbwasse2** [comment]
I added a few new updates. Now kronprod_sparse and kronprodInv are gone. Kronprod_sparse has been replaced by a flag in the kronProd class. KronProdInv can now be accomplish by using the invert() operation in operations.py. I used the paper "On the Kronecker Product" by Kathrin Schacke as inspiration for speed ups and ideas of what to implement.

**Pull request merged**
