### PR TITLE
Requirements issue

### PR DESCRIPTION
**Pull request by Jbwasse2**
Pip version is not consistent with most recent version of git that @alexandroid000 used. I added a requirements.txt file and updated the README.md to allow for appropriate installation of required packages.

### CODE REVIEW

**Comment by alexandroid000** [comment]
Why are there a bunch of other commits in this pull request? Seems like only ab97ff8 should be included

**Comment by Jbwasse2** [comment]
Good catch, I didn't notice those. I will make the appropriate fixes.

**Comment by Jbwasse2** [comment]
I reverted the last 2 commits. Do you have any thoughts on how I should go about reverting a5fb855 and 320537c?

**Comment by Jbwasse2** [comment]
Those commits were done back over the summer to get data about our kron implementation in R.

**Comment by alexandroid000** [comment]
Hmm, I guess they should have been merged back then. But I can merge this one now if they're all  changes we want to put into master. Otherwise you could use `git rebase` to rearrange commits or delete them, etc

**Comment by Jbwasse2** [comment]
Since they are implementations/bug fixes for the R code I feel like it is appropriate to merge them into master.

**Pull request merged**
